name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        go build -v ./...

    #- name: Install and Start Firestore Emulator
     # run: |
      #  npm install -g firebase-tools
       # firebase setup:emulators:firestore
       # FIRESTORE_EMULATOR_HOST=localhost:8081 firebase emulators:start --only firestore --project test-project --import=./firebase_data --export-on-exit=./firebase_data &
       # sleep 10 # Give the emulator time to start

    - name: Test (excluding cache + dashboards_test.go)
      run: |
        go list ./... | grep -v '/cache' | xargs go test -tags=ci -race -cover -v
